# Generated by Django 4.2.27 on 2026-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the client.",
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the client.",
                        max_length=255,
                        verbose_name="full name",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the client.",
                        verbose_name="comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the client was created.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "permissions": [("can_view_all_clients", "Can view all clients")],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Date and time when mailing can start.",
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Date and time when mailing must end.",
                        verbose_name="end time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        help_text="Current status of the mailing.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the mailing was created.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "mailing",
                "verbose_name_plural": "mailings",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_all_mailings", "Can view all mailings"),
                    ("can_disable_mailing", "Can disable mailing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time of the sending attempt.",
                        verbose_name="attempt time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")],
                        help_text="Status of the sending attempt.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Response from the mail server.",
                        verbose_name="server response",
                    ),
                ),
            ],
            options={
                "verbose_name": "mailing attempt",
                "verbose_name_plural": "mailing attempts",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line.",
                        max_length=255,
                        verbose_name="subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Email body content.", verbose_name="body"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the message was created.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "permissions": [("can_view_all_messages", "Can view all messages")],
            },
        ),
    ]
